name: 'Vlocity CICD'
description: 'Vlocity CICD'
inputs:
  Head_Branch:  # id of input
    description: 'Target'
    required: true
    default: 'main'
  Origin_Branch:
    description: 'Origin'
    required: true
    default: ''
  protectedBranches:
    required: true 
    default: 'master,release,develop'
  username:
    required: true
  client_secret:
    required: true
  password:
    required: true
  client_id:
    required: true
  url:
    required: true
outputs:
  Destino: # id of output
      description: 'Target'
  Origen:
      description: 'Origin'
  protectedBranches:
      description: 'protectedBranches'
runs:
  using: 'node12'
  main: 'index/WorkFlow.js'
