# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  CICD:
    runs-on: ubuntu-latest
    name: A job to CICD
    steps:
      # actions/checkout
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      # 
      
      - name: Reading Info
        id: actionInfo
        uses: lawbh93/vlocode_cicd@latest
        with:
          Head_Branch: 'master'
          Origin_Branch:  git branch --show-current
          protectedBranches: 'master,release,develop'

      # Use the output from the `hello` step
      - name: Get the output branchHead
        id: branches
        run: |
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git branch --show-current >> branch.txt
          echo "The output branchHead ${{ steps.actionInfo.outputs.branchHead }}"
          echo "::set-output name=BRANCHNAME::${GITHUB_REF#refs/heads/}"
      - name: ReadInfo2
        id: shaches
        env:
          TARGET: ${{ steps.actionInfo.outputs.branchHead }}
          BRANCH : ${{ steps.branches.outputs.BRANCHNAME }}
        run: |
          bash .sh/temp.sh $TARGET $BRANCH


