# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  CICD:
    runs-on: ubuntu-latest
    name: A job to CICD
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Get info
        id: act1
        uses: lawbh93/vlocode_cicd@latest
        with:
          branch-name: 'master'
      # Use the output from the `hello` step
      - name: Get the output branchHead
        id: branches
        run: |
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git branch --show-current >> branch.txt
          echo "The output branchHead ${{ steps.act1.outputs.branchHead }}"
          echo "::set-output name=BRANCHNAME::${GITHUB_REF#refs/heads/}"
      - name: ReadInfo2
        id: shaches
        env:
          TARGET: ${{ steps.act1.outputs.branchHead }}
          BRANCH : ${{ steps.branches.outputs.BRANCHNAME }}
        run: |
          bash .sh/temp.sh $TARGET $BRANCH


