# This is a basic workflow to help you get started with Actions

name: Ejecución Dinamica
on: [push]

jobs:
  CICD:
    runs-on: ubuntu-latest
    name: A job to CICD
    steps:
      # actions/checkout
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      # 
      - name: get Branch
        id: brancha
        run: |
          echo "::set-output name=BRANCHNAME::${GITHUB_REF#refs/heads/}"
      - name: DataPack Export
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        id: actionInfo
        uses: lawbh93/vlocode_cicd@latest
        with:
          Head_Branch: 'master'
          Origin_Branch:  ${{ steps.brancha.outputs.BRANCHNAME }}
          protectedBranches: 'master,release,develop'
          username: ${{ secrets.USERNAME }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          passToken: ${{ secrets.PASSWORD }}
          client_id: ${{ secrets.CLIENT_ID }}
          url: ${{ secrets.URL }}
          datapackFilePath: './index/datapack.yaml'
          vlocityMetadata: 'DataPackMetadata'
          eventAction: 'checkOnly'
          FilePathsJson: './index/FilePaths.json'
      - name: DataPack Deployment
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        id: actionInfo2
        uses: lawbh93/vlocode_cicd@latest
        with:
          Head_Branch: 'master'
          Origin_Branch:  ${{ steps.brancha.outputs.BRANCHNAME }}
          protectedBranches: 'master,release,develop'
          username: ${{ secrets.USERNAME }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          passToken: ${{ secrets.PASSWORD }}
          client_id: ${{ secrets.CLIENT_ID }}
          url: ${{ secrets.URL }}
          datapackFilePath: './index/datapack.yaml'
          vlocityMetadata: 'DataPackMetadata'
          eventAction: 'deploy'
          FilePathsJson: './index/FilePaths.json'
